In [5]:
#Shardul Rasal
#25070123155


In [18]:
# Declaration oF Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

#Dimension of ARRAY
print(a.ndim)
print(b.ndim)

print(a.shape)
print(b.shape)

print(a.dtype)
print(b.dtype)
display(a.dtype)

#iN buitl functons using Numpy
np.zeros((2,3))

# array([[0.,0.,0.,],
#        [0.,0.,0.,]])

np.ones((3,3))

#array([[1., 1., 1.]
 #      [0., 1., 0.],
 #     [0., 0., 1.]])

print(np.arange(1,11,2))
print(np.linspace(1,10,5))
print(b * 2)
print(a + 5)
print(np.mean(a))
print(np.sum(a))
print(np.median(a))
print(np.max(a))

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64


dtype('int64')

[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]
93.0
651
30.0
500
